# Generated by Django 4.1.1 on 2022-09-28 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('apellidos', models.CharField(max_length=200)),
                ('dni', models.CharField(max_length=8)),
                ('telefono', models.CharField(max_length=12)),
                ('direccion', models.CharField(max_length=300)),
                ('fecha_nacimiento', models.DateField()),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
